import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCond = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["700"],
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${robotoCond.variable} h-full antialiased`}
    >
      <body 
      // style={{
      //   backgroundColor: "#0a0a0a",
      //   backgroundImage: [
      //     "radial-gradient(ellipse at 15% 85%, rgba(32,32,32,0.9) 0%, transparent 45%)",
      //     "radial-gradient(ellipse at 80% 10%, rgba(28,28,28,0.85) 0%, transparent 40%)",
      //     "radial-gradient(ellipse at 60% 60%, rgba(24,24,24,0.8) 0%, transparent 50%)",
      //     "radial-gradient(ellipse at 90% 75%, rgba(30,30,30,0.75) 0%, transparent 38%)",
      //     "radial-gradient(ellipse at 30% 30%, rgba(26,26,26,0.75) 0%, transparent 42%)",
      //   ].join(", "),
      // }}
      >
          {children}
        <Footer />
      </body>
    </html>
  );
}
